import { test, expect } from '@playwright/test'
import { seed, point, fixture } from './helpers'

test('click, repeat click with closed editor, read mode, distant node and drag', async ({ page }) => {
  const errors: string[] = []; page.on('pageerror', (error) => errors.push(error.message))
  await seed(page)
  let p = await point(page, 'beta')
  await page.mouse.click(p.x, p.y)
  await expect(page.locator('.title-input')).toHaveValue('Beta')
  await expect(page.locator('.content-input')).toHaveValue('Beta contents')
  await page.getByRole('button', { name: 'Read', exact: true }).click()
  await expect(page.getByLabel('Rendered note content')).toHaveText('Beta contents')
  await page.getByRole('button', { name: 'Editor', exact: true }).click()
  p = await point(page, 'beta'); await page.mouse.click(p.x, p.y)
  await expect(page.locator('.title-input')).toHaveValue('Beta')
  p = await point(page, 'beta'); await page.mouse.move(p.x, p.y); await page.mouse.down(); await page.mouse.move(p.x + 80, p.y + 40, { steps: 10 }); await page.mouse.up()
  await page.waitForFunction(async () => { const { graphEngine } = await import('/src/engine/graphEngine.ts'); return graphEngine.runtime.positionOf('beta')![0] > 3.2 })
  await page.keyboard.press('Control+s')
  await page.mouse.move(300, 300); await page.mouse.wheel(0, 1100)
  p = await point(page, 'alpha'); await page.mouse.click(p.x, p.y)
  await expect(page.locator('.title-input')).toHaveValue('Alpha')
  expect(errors).toEqual([])
})

test('hover corridor, plus creates a linked note, search still focuses, Escape cancels', async ({ page }) => {
  await seed(page)
  const p = await point(page, 'alpha')
  await page.mouse.move(p.x, p.y); await page.waitForTimeout(250)
  for (let x = 5; x <= 44; x += 5) { await page.mouse.move(p.x + x, p.y); await page.waitForTimeout(25) }
  await page.mouse.move(p.x + 44, p.y); await page.mouse.down(); await page.mouse.move(p.x + 130, p.y - 100, { steps: 10 }); await page.mouse.up()
  await expect(page.locator('.title-input')).toHaveValue('New note')
  await expect(page.locator('.top-stats')).toContainText('3 notes')
  await expect(page.locator('.top-stats')).toContainText('1 links')
  await page.locator('.search-shell input').fill('Beta')
  await page.getByRole('button', { name: 'Beta Second note' }).click()
  await expect(page.locator('.title-input')).toHaveValue('Beta')
  await page.waitForTimeout(600)
  const b = await point(page, 'beta'); await page.mouse.move(b.x, b.y); await page.waitForTimeout(200)
  await page.mouse.move(b.x + 44, b.y); await page.mouse.down(); await page.mouse.move(b.x + 80, b.y + 40); await page.keyboard.press('Escape'); await page.mouse.up()
  await expect(page.locator('.top-stats')).toContainText('3 notes')
})

test('arbitrary binary attachments survive restart and workspace export/import', async ({ page }) => {
  await seed(page)
  const bytes = Buffer.from([0, 255, 128, 50, 13, 10, 200])
  await page.getByLabel('Attach files', { exact: true }).setInputFiles([{ name: 'файл.bin', mimeType: 'application/octet-stream', buffer: bytes }, { name: 'empty.txt', mimeType: 'text/plain', buffer: Buffer.alloc(0) }])
  await expect(page.locator('.attachment-row')).toHaveCount(2)
  await page.keyboard.press('Control+s')
  await expect(page.locator('.save-indicator')).toHaveClass(/saved/)
  await page.reload(); await expect(page.locator('.attachment-row')).toHaveCount(2)
  const [download] = await Promise.all([page.waitForEvent('download'), page.locator('.attachment-name').first().click()])
  const stream = await download.createReadStream(); const chunks: Buffer[] = []; for await (const chunk of stream!) chunks.push(chunk)
  expect(Buffer.concat(chunks)).toEqual(bytes)
  page.on('dialog', (dialog) => dialog.accept())
  await page.locator('.workspace-switcher').click()
  const [exported] = await Promise.all([page.waitForEvent('download'), page.getByRole('button', { name: 'Export…', exact: true }).click()])
  const path = await exported.path()
  await expect(page.locator('.workspace-busy-overlay')).toBeHidden()
  await page.locator('.workspace-switcher').click()
  const [chooser] = await Promise.all([page.waitForEvent('filechooser'), page.getByRole('button', { name: 'Import…', exact: true }).click()])
  await chooser.setFiles(path!)
  await expect(page.locator('.workspace-switcher-name')).toHaveText('Main (2)')
  await expect(page.locator('.attachment-row')).toHaveCount(2)
  const [copy] = await Promise.all([page.waitForEvent('download'), page.locator('.attachment-name').first().click()])
  const reader = await copy.createReadStream(); const roundtrip: Buffer[] = []; for await (const chunk of reader!) roundtrip.push(chunk)
  expect(Buffer.concat(roundtrip)).toEqual(bytes)
  await page.screenshot({ path: 'test-results/attachments.png' })
})

test('workspace create/rename/delete, switching and link tool', async ({ page }) => {
  await seed(page)
  await page.getByRole('button', { name: '↗ New link', exact: true }).click()
  let a = await point(page, 'alpha'), b = await point(page, 'beta')
  await page.mouse.click(a.x, a.y); await page.mouse.click(b.x, b.y)
  await expect(page.locator('.top-stats')).toContainText('1 links')
  await page.getByRole('button', { name: 'Delete link', exact: true }).click()
  await expect(page.locator('.top-stats')).toContainText('0 links')
  page.on('dialog', (dialog) => dialog.accept(dialog.type() === 'prompt' ? 'Other' : undefined))
  await page.locator('.workspace-switcher').click(); await page.getByRole('button', { name: '+ New', exact: true }).click()
  await expect(page.locator('.workspace-switcher-name')).toHaveText('Other')
  await expect(page.locator('.top-stats')).toContainText('0 notes')
  await page.getByRole('button', { name: '+ New node', exact: true }).click()
  await expect(page.locator('.title-input')).toHaveValue('New note')
  await page.locator('.workspace-switcher').click(); await page.locator('.workspace-row').filter({ hasText: 'Main' }).click()
  await expect(page.locator('.top-stats')).toContainText('2 notes')
  await page.locator('.workspace-switcher').click(); await page.getByRole('button', { name: 'Delete', exact: true }).click()
  await expect(page.locator('.workspace-switcher-name')).toHaveText('Other')
  await expect(page.locator('.top-stats')).toContainText('1 notes')
})

test('large graph remains selectable offline; dropped/cancelled connector does not add a note', async ({ page }) => {
  const errors: string[] = []; page.on('pageerror', (error) => errors.push(error.message))
  const externalRequests: string[] = []
  await page.route('**/*', (route) => {
    const url = route.request().url()
    if (/^https?:/.test(url) && !url.startsWith('http://127.0.0.1:5183')) { externalRequests.push(url); return route.abort() }
    return route.continue()
  })
  const nodes = Array.from({ length: 1200 }, (_, i) => ({ id: `n${i}`, title: `Узел ${i}`, summary: 'Проверка кириллицы', content: `Содержимое ${i}`, position: [(i % 40 - 20) * 2, (Math.floor(i / 40) - 15) * 2, 0] }))
  const edges = nodes.slice(1).map((_, i) => ({ id: `e${i}`, source: `n${i}`, target: `n${i + 1}` }))
  for (let i = 0; i < 600; i++) edges.push({ id: `cross${i}`, source: `n${i}`, target: `n${i + 600}` })
  await page.addInitScript((state) => localStorage.setItem('neuron-map-workspace-web-default', JSON.stringify(state)), { ...fixture, nodes, edges, camera: { position: [0, 0, 30], quaternion: [0, 0, 0, 1], orbitTarget: [0, 0, 0] } })
  await page.goto('/'); await expect(page.locator('.top-stats')).toContainText('1200 notes')
  await page.waitForFunction(async () => { const { graphEngine } = await import('/src/engine/graphEngine.ts'); return graphEngine.runtime.ids.length === 1200 })
  const p = await point(page, 'n620')
  await page.mouse.click(p.x, p.y)
  await expect(page.locator('.content-input')).toHaveValue('Содержимое 620')
  await page.mouse.move(p.x, p.y); await page.waitForTimeout(250)
  await page.mouse.move(p.x + 44, p.y); await page.mouse.down(); await page.mouse.move(1300, p.y, { steps: 15 }); await page.mouse.up()
  await expect(page.locator('.top-stats')).toContainText('1200 notes')
  expect(errors).toEqual([])
  expect(externalRequests).toEqual([])
})
