import { test, expect } from '@playwright/test'
import { seed, point, fixture } from './helpers'

async function recovery(page: import('@playwright/test').Page) {
  await page.locator('.workspace-switcher').click()
  await page.getByRole('button', { name: 'Recovery & backups', exact: true }).click()
}

test('deleting a connector source cancels the gesture and undo restores normal selection', async ({ page }) => {
  const errors: string[] = []; page.on('pageerror', e => errors.push(e.message))
  await seed(page)
  const p = await point(page, 'alpha')
  await page.mouse.move(p.x, p.y); await page.waitForTimeout(200)
  await page.mouse.move(p.x + 44, p.y); await page.mouse.down(); await page.mouse.move(p.x + 130, p.y - 50, { steps: 5 })
  await page.keyboard.press('Delete'); await page.mouse.up()
  const b = await point(page, 'beta'); await page.mouse.click(b.x, b.y)
  await expect(page.locator('.title-input')).toHaveValue('Beta')
  await page.getByRole('button', { name: 'Undo', exact: true }).click()
  const a = await point(page, 'alpha'); await page.mouse.click(a.x, a.y)
  await expect(page.locator('.title-input')).toHaveValue('Alpha')
  expect(errors).toEqual([])
})

test('trash and attached bytes survive restart and note restoration', async ({ page }) => {
  await seed(page)
  await page.getByLabel('Attach files', { exact: true }).setInputFiles({ name: 'keep.bin', mimeType: 'application/octet-stream', buffer: Buffer.from([1, 0, 255]) })
  await expect(page.locator('.attachment-row')).toHaveCount(1)
  await page.getByTitle('Move note to Trash').click()
  await page.getByRole('button', { name: 'Save', exact: true }).click()
  await expect(page.locator('.save-indicator')).toHaveClass(/saved/)
  await page.reload(); await expect(page.locator('canvas')).toBeVisible()
  await recovery(page)
  await page.getByRole('button', { name: 'Restore', exact: true }).click()
  await page.getByRole('button', { name: 'Close dialog' }).click()
  await expect(page.locator('.title-input')).toHaveValue('Alpha')
  const [download] = await Promise.all([page.waitForEvent('download'), page.locator('.attachment-name').click()])
  const stream = await download.createReadStream(), chunks: Buffer[] = []; for await (const chunk of stream!) chunks.push(chunk)
  expect(Buffer.concat(chunks)).toEqual(Buffer.from([1, 0, 255]))
})

test('oldest of twenty snapshots restores without losing current unsaved edits', async ({ page }) => {
  await seed(page)
  await page.evaluate(async () => {
    const { useGraphStore } = await import('/src/store/useGraphStore.ts')
    const { flushPersist } = await import('/src/services/persistence.ts')
    for (let i = 0; i < 20; i++) { useGraphStore.getState().updateNode('alpha', { content: `Version ${i}` }); await flushPersist({ createBackup: true }) }
    useGraphStore.getState().updateNode('alpha', { content: 'Unsaved safety copy' })
  })
  page.on('dialog', d => d.accept())
  await recovery(page); await page.getByRole('tab', { name: 'Snapshots', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Restore snapshot', exact: true })).toHaveCount(20)
  await page.getByRole('button', { name: 'Restore snapshot', exact: true }).last().click()
  await expect(page.locator('.content-input')).toHaveValue('Version 0')
  await recovery(page); await page.getByRole('tab', { name: 'Snapshots', exact: true }).click()
  await page.getByRole('button', { name: 'Restore snapshot', exact: true }).first().click()
  await expect(page.locator('.content-input')).toHaveValue('Unsaved safety copy')
})

test('backup copy exports current memory after a failed save', async ({ page }) => {
  await seed(page)
  await page.evaluate(() => {
    const original = Storage.prototype.setItem
    Storage.prototype.setItem = function(key, value) { if (key.startsWith('neuron-map-workspace-')) throw new DOMException('Disk full', 'QuotaExceededError'); original.call(this, key, value) }
  })
  await page.locator('.content-input').fill('Rescue these edits')
  await page.getByRole('button', { name: 'Save', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Retry', exact: true })).toBeVisible()
  page.on('dialog', d => d.accept())
  const [download] = await Promise.all([page.waitForEvent('download'), page.getByRole('button', { name: 'Save backup copy…', exact: true }).click()])
  const stream = await download.createReadStream(), chunks: Buffer[] = []; for await (const chunk of stream!) chunks.push(chunk)
  const payload = JSON.parse(Buffer.concat(chunks).toString())
  expect(payload.version).toBe(3); expect(payload.state.nodes[0].content).toBe('Rescue these edits')
  await expect(page.locator('.save-indicator')).toHaveClass(/error/)
})

test('markdown stays safe and wiki navigation survives rename; tags and history work', async ({ page }) => {
  const external: string[] = []
  page.on('request', request => { if (request.url().startsWith('https://example.invalid')) external.push(request.url()) })
  await seed(page)
  await page.getByRole('button', { name: '⚙', exact: true }).click()
  await page.getByRole('checkbox').first().check(); await page.getByRole('button', { name: '⚙', exact: true }).click()
  await page.locator('.content-input').fill('# Heading\n\n**Bold** [[Beta|Go to Beta]]\n\n<script>window.bad = true</script>\n\n![remote](https://example.invalid/tracker.png)\n\n```js\nconst x = 2\n```')
  await page.getByRole('button', { name: 'Read', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Heading', exact: true })).toBeVisible()
  await expect(page.locator('.markdown-body strong')).toHaveText('Bold')
  await expect(page.locator('.markdown-body .hljs-keyword')).toContainText('const')
  await page.getByRole('button', { name: 'Go to Beta', exact: true }).click()
  await page.locator('.title-input').fill('Renamed Beta')
  await expect(page.getByLabel('Tags', { exact: true })).toHaveCount(1)
  await page.getByLabel('Tags', { exact: true }).fill('research, examples'); await page.getByLabel('Tags', { exact: true }).press('Enter')
  await page.getByRole('button', { name: 'Back to previous note', exact: true }).click()
  await page.getByRole('button', { name: 'Go to Beta', exact: true }).click()
  await expect(page.locator('.title-input')).toHaveValue('Renamed Beta')
  await page.locator('.search-shell input').fill('#research renamed')
  await expect(page.locator('.search-result')).toHaveCount(1)
  expect(external).toEqual([])
  expect(await page.evaluate(() => (window as any).bad)).toBeUndefined()
  await page.screenshot({ path: 'test-results/reading-v022.png' })
})

test('PDF and image previews are local and page controls render the second page', async ({ page }) => {
  const errors: string[] = []; page.on('pageerror', e => errors.push(e.message))
  await seed(page)
  await page.getByLabel('Attach files', { exact: true }).setInputFiles('tests/fixtures/preview.pdf')
  await expect(page.locator('.attachment-row')).toHaveCount(1)
  await page.getByRole('button', { name: 'Preview preview.pdf', exact: true }).click()
  await expect(page.getByLabel('PDF page 1', { exact: true })).toBeVisible()
  await expect(page.getByRole('alert')).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Next page', exact: true })).toBeEnabled({ timeout: 10000 })
  await page.getByRole('button', { name: 'Next page', exact: true }).click()
  await expect(page.getByLabel('PDF page 2', { exact: true })).toBeVisible()
  await expect(page.getByRole('alert')).toHaveCount(0)
  await page.getByRole('button', { name: 'Close dialog' }).click()
  await page.getByLabel('Attach files', { exact: true }).setInputFiles({ name: 'pixel.png', mimeType: 'image/png', buffer: Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAusB9Y9Zl1sAAAAASUVORK5CYII=', 'base64') })
  await expect(page.locator('.attachment-row')).toHaveCount(2)
  await page.getByRole('button', { name: 'Preview pixel.png', exact: true }).click()
  await expect(page.getByRole('dialog').getByRole('img')).toBeVisible()
  await expect.poll(() => page.getByRole('dialog').getByRole('img').evaluate(image => (image as HTMLImageElement).naturalWidth)).toBeGreaterThan(0)
  expect(errors).toEqual([])
})

test('idle particles reuse link geometry and reduced motion stops their updates', async ({ page }) => {
  await seed(page, { ...fixture, edges: [{ id: 'edge', source: 'alpha', target: 'beta' }] } as typeof fixture)
  const count = () => page.evaluate(async () => (await import('/src/components/OptimizedGraphLayer.tsx')).graphDiagnostics.edgeGeometryBuilds)
  await page.waitForTimeout(700)
  const before = await count(); await page.waitForTimeout(500)
  expect(await count()).toBe(before)
  await page.getByRole('button', { name: '⚙', exact: true }).click(); await page.getByRole('checkbox').nth(1).check()
  await page.getByRole('button', { name: '⚙', exact: true }).click()
  await page.getByRole('button', { name: 'Show neighbors', exact: true }).click()
  await expect(page.locator('.neighborhood-banner')).toBeVisible()
})

test('a stale browser tab reports a conflict instead of overwriting new edits', async ({ page, context }) => {
  await seed(page)
  const other = await context.newPage()
  await other.goto('/'); await expect(other.locator('.title-input')).toHaveValue('Alpha')
  await page.locator('.content-input').fill('Saved by the first tab')
  await page.getByRole('button', { name: 'Save', exact: true }).click(); await expect(page.locator('.save-indicator')).toHaveClass(/saved/)
  await other.locator('.content-input').fill('Stale second tab edit')
  await other.getByRole('button', { name: 'Save', exact: true }).click()
  await expect(other.locator('.workspace-error-banner')).toContainText('SAVE_CONFLICT')
  const content = await page.evaluate(() => JSON.parse(localStorage.getItem('neuron-map-workspace-web-default')!).nodes[0].content)
  expect(content).toBe('Saved by the first tab')
  await other.close()
})
